// <auto-generated />
using System;
using EFInheritance.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFInheritance.Migrations
{
    [DbContext(typeof(EFDbContext))]
    [Migration("20240118020132_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EFInheritance.Models.Employee", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Employees", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("EFInheritance.Models.Developer", b =>
                {
                    b.HasBaseType("EFInheritance.Models.Employee");

                    b.Property<string>("softWare")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.ToTable("DEVELOPERS");
                });

            modelBuilder.Entity("EFInheritance.Models.Manager", b =>
                {
                    b.HasBaseType("EFInheritance.Models.Employee");

                    b.Property<string>("Department")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.ToTable("MANAGERS");
                });

            modelBuilder.Entity("EFInheritance.Models.Developer", b =>
                {
                    b.HasOne("EFInheritance.Models.Employee", null)
                        .WithOne()
                        .HasForeignKey("EFInheritance.Models.Developer", "ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EFInheritance.Models.Manager", b =>
                {
                    b.HasOne("EFInheritance.Models.Employee", null)
                        .WithOne()
                        .HasForeignKey("EFInheritance.Models.Manager", "ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
